# Generated by Django 6.0.7 on 2026-07-07 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='scenes/audio/')),
                ('prefab_key', models.CharField(max_length=120)),
                ('qr_code', models.CharField(blank=True, max_length=80, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='scenes/qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='catalog.book')),
            ],
            options={
                'ordering': ['book', 'order', 'id'],
            },
        ),
    ]
