# Generated by Django 6.0.7 on 2026-07-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='glb_model',
            field=models.FileField(blank=True, null=True, upload_to='scenes/models/'),
        ),
    ]
