# Generated by Django 6.0.7 on 2026-09-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_scene_ar_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='prefab_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
